//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 07:25:52 PM CEST 
//

package com.team32.AgentApp.model.entitet;

import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.GregorianCalendar;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.xml.bind.DatatypeConverter;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.team32.AgentApp.soap.LocalDateTimeAdapter;

/**
 * <p>
 * Java class for common_data complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="common_data">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Datum_kreiranja" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Datum_izmene" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Korisnik" type="{http://www.ftn.uns.ac.rs/korisnici}TUser"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommonData", namespace = "http://www.ftn.uns.ac.rs/sync", propOrder = { "id", "datumKreiranja","datumIzmene","userId"})

@Entity
@XmlRootElement(name = "CommonData", namespace = "http://www.ftn.uns.ac.rs/sync")
public class CommonData {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@XmlElement(name = "Id", required = true)
	protected Long id;

	@Column(name = "datum_kreiranja", nullable = false)
	@XmlElement(name = "DatumKreiranja", required = true)
	@XmlSchemaType(name = "dateTime")
	@XmlJavaTypeAdapter(LocalDateTimeAdapter.class)
	protected LocalDateTime datumKreiranja;

	@Column(name = "datum_izmene")
	@XmlElement(name = "DatumIzmene", required = true)
	@XmlSchemaType(name = "dateTime")
	@XmlJavaTypeAdapter(LocalDateTimeAdapter.class)
	protected LocalDateTime datumIzmene;

	//Jedna promena(commonData) se odnosi na samo jednog korisnika
	@XmlElement(name = "UserId")
	@Column(name = "korisnik_id")
	protected Long userId;
	
	public CommonData() {
		super();
	}
	public CommonData(Long userId) {
		super();
		this.setDatumKreiranja(LocalDateTime.now());
		this.setDatumIzmene(LocalDateTime.now());
		this.setId(null);
		this.setUserId(userId);
	}
	public CommonData(Long id, LocalDateTime datumKreiranja, LocalDateTime datumIzmene, Long userId) {
		super();
		this.id = id;
		this.datumKreiranja = datumKreiranja;
		this.datumIzmene = datumIzmene;
		this.userId = userId;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public LocalDateTime  getDatumKreiranja() {
		return datumKreiranja;
	}

	public void setDatumKreiranja(LocalDateTime  value) {
		this.datumKreiranja = value;
	}

	public LocalDateTime  getDatumIzmene() {
		return datumIzmene;
	}

	public void setDatumIzmene(LocalDateTime  value) {
		this.datumIzmene = value;
	}
	
	public Long getUserid() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}
	public void setDatumKreiranja(String datumKreiranja) {
		DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
		LocalDateTime dateTime = LocalDateTime.parse(datumKreiranja.replace('T',' ' ), formatter);
		this.datumKreiranja = dateTime;
		
	}

	public void setDatumIzmene(String datumIzmene) {
		if(datumIzmene.equals(null)) {
			this.datumIzmene=null;
		}else {
		DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
		LocalDateTime dateTime = LocalDateTime.parse(datumIzmene.replace('T',' ' ), formatter);
		this.datumIzmene = dateTime;	
		}
	}
}
