//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 07:25:52 PM CEST 

package com.team32.AgentApp.model.entitet;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

//import com.example.Messages.SchemaToJava2.model.user.RegistrovaniKorisnik;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Korisnik" type="{http://www.ftn.uns.ac.rs/AdminKlijent}common_data"/>
 *         &lt;element name="Vrednost_ocene">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Ocena", namespace = "http://www.ftn.uns.ac.rs/sync", propOrder = { "id", "commonDataId", "vrednostOcene","automobilId","rezervacijaId","autor" })
@XmlRootElement(name = "Ocena", namespace = "http://www.ftn.uns.ac.rs/sync")
@Entity
public class Ocena {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@XmlElement(name = "Id", required = true)
	protected Long id;

	@Column(name = "vredn_ocene")
	@XmlElement(name = "VrednostOcene", required = true)
	protected int vrednostOcene;
	
    @Column(name="automobil_id")
    @XmlElement(name = "AutomobilId", required = true)
    private Long automobilId;
    
    @Column(name="rezervacija_id")
    @XmlElement(name = "RezervacijaId", required = true)
    private Long rezervacijaId;

    @Column(name="common_data_id")
    @XmlElement(name = "CommonDataId", required = true)
    protected Long commonDataId;
    
    //dodato
	@XmlElement(name = "Autor", required = true)
	private String autor;
    

	public Ocena() {
		super();
	}

	public Ocena(Long id, int vrednostOcene, Long automobilId, Long rezervacijaId, Long commonDataId) {
		super();
		this.id = id;
		this.vrednostOcene = vrednostOcene;
		this.automobilId = automobilId;
		this.rezervacijaId = rezervacijaId;
		this.commonDataId = commonDataId;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long value) {
		this.id = value;
	}

	public int getVrednostOcene() {
		return vrednostOcene;
	}

	public void setVrednostOcene(int value) {
		this.vrednostOcene = value;
	}
	
	public Long getAutomobilId() {
		return automobilId;
	}

	public void setAutomobilId(Long automobilId) {
		this.automobilId = automobilId;
	}

	public Long getRezervacijaId() {
		return rezervacijaId;
	}

	public void setRezervacijaId(Long rezervacijaId) {
		this.rezervacijaId = rezervacijaId;
	}

	public Long getCommonDataId() {
		return commonDataId;
	}

	public void setCommonDataId(Long commonDataId) {
		this.commonDataId = commonDataId;
	}

}
