//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 07:25:52 PM CEST 
//

package com.team32.AgentApp.model.entitet;

import java.time.LocalDateTime;
import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.team32.AgentApp.soap.LocalDateTimeAdapter;

//import com.example.Messages.SchemaToJava2.model.user.Firma;
//import com.example.Messages.SchemaToJava2.model.user.RegistrovaniKorisnik;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/Automobil}Automobil"/>
 *         &lt;element name="Od_datuma" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Do_datuma" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/cenovnik}Cenovnik"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", namespace = "http://www.ftn.uns.ac.rs/sync", propOrder = { "id", "commonDataId", "odDatuma","doDatuma",
		"cenovnikId","automobilId","planiranaKilometraza","adresaId", "username" })

@XmlRootElement(name = "Oglas", namespace = "http://www.ftn.uns.ac.rs/sync")
@Entity 
public class Oglas {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@XmlElement(name = "Id", required = true)
    protected Long id; 
    
//  @XmlSchemaType(name = "dateTime")
    @Column(name = "od_datuma", nullable = false)
    @XmlElement(name = "OdDatuma", required = true)
	@XmlJavaTypeAdapter(LocalDateTimeAdapter.class)
    protected LocalDateTime odDatuma;
	
//  @XmlSchemaType(name = "dateTime")
    @Column(name = "do_datuma", nullable = false)
    @XmlElement(name = "DoDatuma", required = true)
	@XmlJavaTypeAdapter(LocalDateTimeAdapter.class)
    protected LocalDateTime  doDatuma;
    
    @Column(name = "adresa_id", nullable = false)
    @XmlElement(name = "AdresaId", required = true)
    protected Long adresaId;
    
    @Column(name="cenovnik_id")
	@XmlElement(name = "CenovnikId", required = true)
    protected Long cenovnikId;
	
    @Column(name="automobil_id")
    @XmlElement(name = "AutomobilId", required = true)
	private Long automobilId;
    
    @Column(name="plan_km")
    @XmlElement(name = "PlaniranaKm", required = true)
    private float planiranaKilometraza;
    
    @Column(name="common_data_id")
    @XmlElement(name = "CommonDataId", required = true)
	private Long commonDataId;
    
    //dodato
	@XmlElement(name = "Username", required = true)
	private String username;
    
    public Oglas() {
		super();
	}
    
    public Oglas(Long id, LocalDateTime  odDatuma, LocalDateTime  doDatuma, Long adresaId, Long cenovnikId, Long automobilId,
    		float planiranaKilometraza, Long commonDataId) {
		super();
		this.id = id;
		this.odDatuma = odDatuma;
		this.doDatuma = doDatuma;
		this.adresaId = adresaId;
		this.cenovnikId = cenovnikId;
		this.automobilId = automobilId;
		this.planiranaKilometraza =  planiranaKilometraza;
		this.commonDataId = commonDataId;
	}

	public Long getId() {
        return id;
    }

	public void setId(Long value) {
        this.id = value;
    }


    public LocalDateTime  getOdDatuma() {
        return odDatuma;
    }


    public void setOdDatuma(LocalDateTime value) {
        this.odDatuma = value;
    }

    
    public LocalDateTime getDoDatuma() {
        return doDatuma;
    }


    public void setDoDatuma(LocalDateTime value) {
        this.doDatuma = value;
    }


	public Long getAdresaId() {
		return adresaId;
	}

	public void setAdresaId(Long adresaId) {
		this.adresaId = adresaId;
	}

	public Long getCenovnikId() {
		return cenovnikId;
	}


	public void setCenovnikId(Long cenovnikId) {
		this.cenovnikId = cenovnikId;
	}

	public Long getAutomobilId() {
		return automobilId;
	}


	public void setAutomobilId(Long automobilId) {
		this.automobilId = automobilId;
	}
	
	public float getPlaniranaKilometraza() {
		return planiranaKilometraza;
	}

	public void setPlaniranaKilometraza(float planiranaKilometraza) {
		this.planiranaKilometraza = planiranaKilometraza;
	}

	public Long getCommonDataId() {
		return commonDataId;
	}


	public void setCommonDataId(Long commonDataId) {
		this.commonDataId = commonDataId;
	}
}
