//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 07:25:52 PM CEST 
//

package com.team32.AgentApp.model.tentitet;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for TAdresa complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TAdresa">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Mesto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Postanski_broj" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Ulica" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Broj" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Kordinate" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="longitude">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *                       &lt;minInclusive value="0"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="latitude">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *                       &lt;minInclusive value="0"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@XmlAccessorType(XmlAccessType.FIELD)
@Entity
@XmlType(name = "TAdresa", namespace = "http://www.ftn.uns.ac.rs/sync", propOrder = {
    "id",
    "mesto",
    "postanskiBroj",
    "ulica",
    "broj",
    "kordinate"
})

@XmlRootElement(name = "TAdresa", namespace = "http://www.ftn.uns.ac.rs/sync")
public class Adresa {
	
	@Id
	@XmlElement(name = "Id", required = true)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    protected Long id;
	
	@Column(name = "mesto", nullable = false)
    @XmlElement(name = "Mesto", required = true)
    protected String mesto;
    
	@Column(name = "postanski_broj", nullable = false)
    @XmlElement(name = "PostanskiBroj")
    protected String postanskiBroj;
    
	@Column(name = "ulica", nullable = false)
    @XmlElement(name = "Ulica", required = true)
    protected String ulica;
    
	@Column(name = "broj")
    @XmlElement(name = "Broj")
    protected String broj;

	
	@Column(name="common_data_id", nullable = false)
	@XmlElement(name = "CommonDataId", required = true)
	private Long commonDataId;

    public Adresa() {
		super();
	}

	public Adresa(Long id, String mesto, String postanskiBroj, String ulica, String broj, /*Long oglasId, Long userId,*/Long commonDataId) {
		super();
		this.id = id;
		this.mesto = mesto;
		this.postanskiBroj = postanskiBroj;
		this.ulica = ulica;
		this.broj = broj;
		this.commonDataId = commonDataId;
	}

	public Long getId() {
        return id;
    }

    public void setId(Long value) {
        this.id = value;
    }

    public String getMesto() {
        return mesto;
    }

    public void setMesto(String value) {
        this.mesto = value;
    }

    public String getPostanskiBroj() {
        return postanskiBroj;
    }

    public void setPostanskiBroj(String value) {
        this.postanskiBroj = value;
    }

    public String getUlica() {
        return ulica;
    }

    public void setUlica(String value) {
        this.ulica = value;
    }

    public String getBroj() {
        return broj;
    }

    public void setBroj(String value) {
        this.broj = value;
    }

	public Long getCommonDataId() {
		return commonDataId;
	}

	public void setCommonDataId(Long commonDataId) {
		this.commonDataId = commonDataId;
	}

}
