
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 07:25:52 PM CEST 

package com.team32.AgentApp.model.entitet;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for TUser complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TUser">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Korisnicko_ime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Lozinka" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Adresa" type="{http://www.ftn.uns.ac.rs/korisnici}TAdresa"/>
 *         &lt;element name="Email" type="{http://www.ftn.uns.ac.rs/korisnici}TEmail"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/korisnici}Status"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TUser", namespace = "http://www.ftn.uns.ac.rs/korisnici", propOrder = {
    "id",
    "korisnickoIme",
    "lozinka",
    "adresa",
    "email",
    "status"
})
@XmlSeeAlso({

})

@Entity
@Table(name="Users")
public class User /*implements UserDetails */ {
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    protected Long id;
	
	@Column(name = "korisnicko_ime", unique = true, nullable = false)
    @XmlElement(name = "Korisnicko_ime", required = true)
    protected String korisnickoIme;
	
	@Column(name = "lozinka", nullable = false)
    @XmlElement(name = "Lozinka", required = true)
    protected String lozinka;
	
	@Column(name = "email", nullable = false)
    @XmlElement(name = "Email", required = true)
    protected String email;
	
	@Column(name = "status", nullable = false)
    @XmlElement(name = "Status", required = true, defaultValue = "aktivan")
    protected String status;
	
    @XmlElement(name = "Adresa", required = true)
    @Column(name = "adresa_id", nullable = false)
    protected Long adresaId;
    
	//za agenta osoba
    
	@Column(name = "ime",  nullable = true)
    @XmlElement(name = "Ime", namespace = "http://www.ftn.uns.ac.rs/korisnici", required = true)
    protected String ime;
    
	@Column(name = "prezime",  nullable = true)
    @XmlElement(name = "Prezime", namespace = "http://www.ftn.uns.ac.rs/korisnici", required = true)
    protected String prezime;
    
	@Column(name = "jmbg",  nullable = true)
    @XmlElement(name = "JMBG", namespace = "http://www.ftn.uns.ac.rs/korisnici", required = true)
    protected String jmbg;
    
	//za agenta firma
	
    @Column(name = "naziv",  nullable = true)
    @XmlElement(name = "Naziv", namespace = "http://www.ftn.uns.ac.rs/korisnici")
    protected String naziv;
	
	@Column(name = "pib", unique = true, nullable = true)
    @XmlElement(name = "poslovni_maticni_broj", namespace = "http://www.ftn.uns.ac.rs/korisnici", required = true)
    protected String poslovniMaticniBroj;
	
    @Column(name="common_data_id", nullable = false)
    protected Long commonDataId;
    
    protected String pol;

	public User() {
		super();
	}

	public User(Long id, String korisnickoIme, String lozinka, String email, String status, Long adresaId, String ime,
			String prezime, String jmbg, String naziv, String poslovniMaticniBroj, String pol, Long commonDataId) {
		super();
		this.id = id;
		this.korisnickoIme = korisnickoIme;
		this.lozinka = lozinka;
		this.email = email;
		this.status = status;
		this.adresaId = adresaId;
		this.ime = ime;
		this.prezime = prezime;
		this.jmbg = jmbg;
		this.naziv = naziv;
		this.poslovniMaticniBroj = poslovniMaticniBroj;
		this.commonDataId = commonDataId;
		this.pol = pol;
	}

	public Long getId() {
        return id;
    }

	public void setId(Long value) {
        this.id = value;
    }


    public String getKorisnickoIme() {
        return korisnickoIme;
    }


    public void setKorisnickoIme(String value) {
        this.korisnickoIme = value;
    }


    public String getLozinka() {
        return lozinka;
    }


    public void setLozinka(String value) {
        this.lozinka = value;
    }

    public Long getAdresaId() {
		return adresaId;
	}


	public void setAdresaId(Long adresaId) {
		this.adresaId = adresaId;
	}


    public String getEmail() {
        return email;
    }


    public void setEmail(String value) {
        this.email = value;
    }


    public String getStatus() {
        return status;
    }


    public void setStatus(String value) {
        this.status = value;
    }
    
    public String getPoslovniMaticniBroj() {
        return poslovniMaticniBroj;
    }

	public String getNaziv() {
		return naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	public String getIme() {
		return ime;
	}

	public void setIme(String ime) {
		this.ime = ime;
	}

	public String getPrezime() {
		return prezime;
	}

	public void setPrezime(String prezime) {
		this.prezime = prezime;
	}

	public String getJmbg() {
		return jmbg;
	}

	public void setJmbg(String jmbg) {
		this.jmbg = jmbg;
	}
	
	public String getPol() {
		return pol;
	}

	public void setPol(String pol) {
		this.pol = pol;
	}

	public void setPoslovniMaticniBroj(String value) {
        this.poslovniMaticniBroj = value;
    }
	
	public Long getCommonDataId() {
		return commonDataId;
	}

	public void setCommonDataId(Long commonDataId) {
		this.commonDataId = commonDataId;
	}

}
