//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 04:31:20 PM CEST 
//


package schemaToJava;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ftn.uns.ac.rs/AdminKlijent}common_data">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/korisnici}Firma"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "firma"
})
@XmlRootElement(name = "CommonDataFirma", namespace = "http://www.ftn.uns.ac.rs/AdminKlijent")
public class CommonDataFirma
    extends CommonData
{

    @XmlElement(name = "Firma", namespace = "http://www.ftn.uns.ac.rs/korisnici", required = true)
    protected Firma firma;

    /**
     * Gets the value of the firma property.
     * 
     * @return
     *     possible object is
     *     {@link Firma }
     *     
     */
    public Firma getFirma() {
        return firma;
    }

    /**
     * Sets the value of the firma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Firma }
     *     
     */
    public void setFirma(Firma value) {
        this.firma = value;
    }

}
