//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 04:31:20 PM CEST 
//


package schemaToJava;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Datum_preuzimanja_vozila" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Datum_povratka_vozila" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Mesto_preuzimanja_vozila" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MinCena" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="MaxCena" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="Dodatni_parametri" type="{http://www.ftn.uns.ac.rs/Automobil}TAutomobila"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datumPreuzimanjaVozila",
    "datumPovratkaVozila",
    "mestoPreuzimanjaVozila",
    "minCena",
    "maxCena",
    "dodatniParametri"
})
@XmlRootElement(name = "Pretrazivanje", namespace = "http://www.ftn.uns.ac.rs/KorisnickiModul")
public class Pretrazivanje {

    @XmlElement(name = "Datum_preuzimanja_vozila", namespace = "http://www.ftn.uns.ac.rs/KorisnickiModul", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datumPreuzimanjaVozila;
    @XmlElement(name = "Datum_povratka_vozila", namespace = "http://www.ftn.uns.ac.rs/KorisnickiModul", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datumPovratkaVozila;
    @XmlElement(name = "Mesto_preuzimanja_vozila", namespace = "http://www.ftn.uns.ac.rs/KorisnickiModul", required = true)
    protected String mestoPreuzimanjaVozila;
    @XmlElement(name = "MinCena", namespace = "http://www.ftn.uns.ac.rs/KorisnickiModul", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger minCena;
    @XmlElement(name = "MaxCena", namespace = "http://www.ftn.uns.ac.rs/KorisnickiModul", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger maxCena;
    @XmlElement(name = "Dodatni_parametri", namespace = "http://www.ftn.uns.ac.rs/KorisnickiModul", required = true)
    protected TAutomobila dodatniParametri;

    /**
     * Gets the value of the datumPreuzimanjaVozila property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPreuzimanjaVozila() {
        return datumPreuzimanjaVozila;
    }

    /**
     * Sets the value of the datumPreuzimanjaVozila property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPreuzimanjaVozila(XMLGregorianCalendar value) {
        this.datumPreuzimanjaVozila = value;
    }

    /**
     * Gets the value of the datumPovratkaVozila property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPovratkaVozila() {
        return datumPovratkaVozila;
    }

    /**
     * Sets the value of the datumPovratkaVozila property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPovratkaVozila(XMLGregorianCalendar value) {
        this.datumPovratkaVozila = value;
    }

    /**
     * Gets the value of the mestoPreuzimanjaVozila property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMestoPreuzimanjaVozila() {
        return mestoPreuzimanjaVozila;
    }

    /**
     * Sets the value of the mestoPreuzimanjaVozila property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMestoPreuzimanjaVozila(String value) {
        this.mestoPreuzimanjaVozila = value;
    }

    /**
     * Gets the value of the minCena property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinCena() {
        return minCena;
    }

    /**
     * Sets the value of the minCena property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinCena(BigInteger value) {
        this.minCena = value;
    }

    /**
     * Gets the value of the maxCena property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxCena() {
        return maxCena;
    }

    /**
     * Sets the value of the maxCena property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxCena(BigInteger value) {
        this.maxCena = value;
    }

    /**
     * Gets the value of the dodatniParametri property.
     * 
     * @return
     *     possible object is
     *     {@link TAutomobila }
     *     
     */
    public TAutomobila getDodatniParametri() {
        return dodatniParametri;
    }

    /**
     * Sets the value of the dodatniParametri property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAutomobila }
     *     
     */
    public void setDodatniParametri(TAutomobila value) {
        this.dodatniParametri = value;
    }

}
