//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 07:25:52 PM CEST 
//


package com.example.Messages.SchemaToJava2.model.tentitet;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TAdresa complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TAdresa">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Mesto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Postanski_broj" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Ulica" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Broj" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Kordinate" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="longitude">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *                       &lt;minInclusive value="0"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="latitude">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *                       &lt;minInclusive value="0"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@XmlAccessorType(XmlAccessType.FIELD)
@Entity
@XmlType(name = "TAdresa", namespace = "http://www.ftn.uns.ac.rs/korisnici", propOrder = {
    "id",
    "mesto",
    "postanskiBroj",
    "ulica",
    "broj",
    "kordinate"
})
public class TAdresa {
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    protected long id;
	
	@Column(name = "mesto", nullable = false)
    @XmlElement(name = "Mesto", required = true)
    protected String mesto;
    
	@Column(name = "postanski_broj", nullable = false)
    @XmlElement(name = "Postanski_broj")
    protected int postanskiBroj;
    
	@Column(name = "ulica", nullable = false)
    @XmlElement(name = "Ulica", required = true)
    protected String ulica;
    
	@Column(name = "broj")
    @XmlElement(name = "Broj")
    protected int broj;
    
	@OneToOne(fetch = FetchType.LAZY)
    @XmlElement(name = "Kordinate")
    protected TAdresa.Kordinate kordinate;


    public long getId() {
        return id;
    }


    public void setId(long value) {
        this.id = value;
    }


    public String getMesto() {
        return mesto;
    }


    public void setMesto(String value) {
        this.mesto = value;
    }


    public int getPostanskiBroj() {
        return postanskiBroj;
    }


    public void setPostanskiBroj(int value) {
        this.postanskiBroj = value;
    }


    public String getUlica() {
        return ulica;
    }


    public void setUlica(String value) {
        this.ulica = value;
    }


    public int getBroj() {
        return broj;
    }


    public void setBroj(int value) {
        this.broj = value;
    }


    public TAdresa.Kordinate getKordinate() {
        return kordinate;
    }


    
    public void setKordinate(TAdresa.Kordinate value) {
        this.kordinate = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="longitude">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
     *             &lt;minInclusive value="0"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="latitude">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
     *             &lt;minInclusive value="0"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    @Entity
    public static class Kordinate {

    	@Id
    	@GeneratedValue(strategy = GenerationType.IDENTITY)
        @XmlElement(namespace = "http://www.ftn.uns.ac.rs/KreiranjeOglasa")
        protected long id;
    	
    	@Column(name = "longitude", nullable = false)
        @XmlAttribute(name = "longitude")
        protected Float longitude;
        
    	@Column(name = "latitude", nullable = false)
        @XmlAttribute(name = "latitude")
        protected Float latitude;

       
        public long getId() {
			return id;
		}


		public void setId(long id) {
			this.id = id;
		}


		public Float getLongitude() {
            return longitude;
        }


        public void setLongitude(Float value) {
            this.longitude = value;
        }


        public Float getLatitude() {
            return latitude;
        }

        public void setLatitude(Float value) {
            this.latitude = value;
        }

    }

}
