//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 07:25:52 PM CEST 
//


package com.example.Messages.SchemaToJava2.model.tentitet;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

import com.example.Messages.SchemaToJava2.model.entitet.Automobil;


/**
 * <p>Java class for TAutomobila complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TAutomobila">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Marka_automobila" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Model_automobila" type="{http://www.ftn.uns.ac.rs/Automobil}TModel_automobila"/>
 *         &lt;element name="Klasa_automobila" type="{http://www.ftn.uns.ac.rs/Automobil}TKlasa_automobila"/>
 *         &lt;element name="Vrsta_goriva" type="{http://www.ftn.uns.ac.rs/Automobil}TTip_goriva"/>
 *         &lt;element name="Tip_menjaca" type="{http://www.ftn.uns.ac.rs/Automobil}TTip_menjaca"/>
 *         &lt;element name="Predjena_kilometraza" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="Planirana_kilometraza" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="Collision_Damage_Waiver" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Broj_sedista_za_decu">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Slika" type="{http://www.ftn.uns.ac.rs/Automobil}TSlika_vozila" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TAutomobila", propOrder = {
    "markaAutomobila",
    "modelAutomobila",
    "klasaAutomobila",
    "vrstaGoriva",
    "tipMenjaca",
    "predjenaKilometraza",
    "planiranaKilometraza",
    "collisionDamageWaiver",
    "brojSedistaZaDecu",
    "slika"
})
@XmlSeeAlso({
    Automobil.class
})
@Entity(name="Automobili")
@Inheritance(strategy = InheritanceType.JOINED)
public class TAutomobila {
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@OneToOne(fetch = FetchType.LAZY)
    @XmlElement(name = "Marka_automobila", required = true)
    protected TMarkaAutomobila markaAutomobila;
    
	@OneToOne(fetch = FetchType.LAZY)
    @XmlElement(name = "Model_automobila", required = true)
    protected TModelAutomobila modelAutomobila;
    
	@OneToOne(fetch = FetchType.LAZY)
    @XmlElement(name = "Klasa_automobila", required = true)
    protected TKlasaAutomobila klasaAutomobila;
    
	@OneToOne(fetch = FetchType.LAZY)
    @XmlElement(name = "Vrsta_goriva", required = true)
    protected TTipGoriva vrstaGoriva;
    
	@OneToOne(fetch = FetchType.LAZY)
    @XmlElement(name = "Tip_menjaca", required = true)
    protected TTipMenjaca tipMenjaca;
    
	@Column(name = "predj_kilom", nullable = false)
    @XmlElement(name = "Predjena_kilometraza")
    protected float predjenaKilometraza;
    
	@Column(name = "plan_kilom", nullable = false)
    @XmlElement(name = "Planirana_kilometraza", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger planiranaKilometraza;
    
	@Column(name = "col_dmg_waiver", nullable = false)
    @XmlElement(name = "Collision_Damage_Waiver")
    protected boolean collisionDamageWaiver;
    
	@Column(name = "br_sedista_za_decu", nullable = false)
    @XmlElement(name = "Broj_sedista_za_decu")
    protected int brojSedistaZaDecu;
    
    @OneToMany(mappedBy = "tAutomobila", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @XmlElement(name = "Slika", required = true)
    protected List<TSlikaVozila> slika;


    public Long getId() {
		return id;
	}


	public void setId(Long id) {
		this.id = id;
	}


	public TMarkaAutomobila getMarkaAutomobila() {
		return markaAutomobila;
	}


	public void setMarkaAutomobila(TMarkaAutomobila markaAutomobila) {
		this.markaAutomobila = markaAutomobila;
	}


	public void setSlika(List<TSlikaVozila> slika) {
		this.slika = slika;
	}


	public TModelAutomobila getModelAutomobila() {
        return modelAutomobila;
    }


    public void setModelAutomobila(TModelAutomobila value) {
        this.modelAutomobila = value;
    }


    public TKlasaAutomobila getKlasaAutomobila() {
        return klasaAutomobila;
    }


    public void setKlasaAutomobila(TKlasaAutomobila value) {
        this.klasaAutomobila = value;
    }

    
    public TTipGoriva getVrstaGoriva() {
        return vrstaGoriva;
    }


    public void setVrstaGoriva(TTipGoriva value) {
        this.vrstaGoriva = value;
    }


    public TTipMenjaca getTipMenjaca() {
        return tipMenjaca;
    }


    public void setTipMenjaca(TTipMenjaca value) {
        this.tipMenjaca = value;
    }


    public float getPredjenaKilometraza() {
        return predjenaKilometraza;
    }


    public void setPredjenaKilometraza(float value) {
        this.predjenaKilometraza = value;
    }


    public BigInteger getPlaniranaKilometraza() {
        return planiranaKilometraza;
    }


    public void setPlaniranaKilometraza(BigInteger value) {
        this.planiranaKilometraza = value;
    }

   
    public boolean isCollisionDamageWaiver() {
        return collisionDamageWaiver;
    }


    public void setCollisionDamageWaiver(boolean value) {
        this.collisionDamageWaiver = value;
    }


    public int getBrojSedistaZaDecu() {
        return brojSedistaZaDecu;
    }


    public void setBrojSedistaZaDecu(int value) {
        this.brojSedistaZaDecu = value;
    }

    public List<TSlikaVozila> getSlika() {
        if (slika == null) {
            slika = new ArrayList<TSlikaVozila>();
        }
        return this.slika;
    }

}
