//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 07:25:52 PM CEST 
//


package com.example.Messages.SchemaToJava2.model.tentitet;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.example.Messages.SchemaToJava2.model.entitet.Automobil;
import com.example.Messages.SchemaToJava2.model.entitet.CommonData;


/**
 * <p>Java class for TModel_automobila complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TModel_automobila">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="naziv_modela" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Common_data" type="{http://www.ftn.uns.ac.rs/AdminKlijent}common_data"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TModel_automobila", propOrder = {
    "id",
    "nazivModela",
    "commonData"
})
@Entity(name="ModelAutomobila")
public class TModelAutomobila {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    protected Long id;
	
	  
	@Column(name = "naziv_modela", nullable = false)
    @XmlElement(name = "naziv_modela", required = true)
    protected String nazivModela;
	
	@OneToOne(fetch = FetchType.LAZY)
    @XmlElement(name = "Common_data", required = true)
    protected CommonData commonData;
    
	//Jedan TModelAutomobilaa se odnosi na samo jednu TMarkaAutomobila(druga strana bidirekcije)
    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private TMarkaAutomobila markaAutomobila;

    //Jedan model ima vise automobila, id marke se dodaje kao nova kolona u tabeli TMarkaAutombila
  	@OneToMany(mappedBy = "modelAutomobila", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
  	protected List<Automobil> automobil;

  	
    public TModelAutomobila(Long id, String nazivModela, CommonData commonData, TMarkaAutomobila markaAutomobila,
			List<Automobil> automobil) {
		super();
		this.id = id;
		this.nazivModela = nazivModela;
		this.commonData = commonData;
		this.markaAutomobila = markaAutomobila;
		this.automobil = automobil;
	}
    

	public TModelAutomobila() {
		super();
	}

	public Long getId() {
        return id;
    }


    public void setId(Long value) {
        this.id = value;
    }


    public String getNazivModela() {
        return nazivModela;
    }


    public void setNazivModela(String value) {
        this.nazivModela = value;
    }


    public CommonData getCommonData() {
        return commonData;
    }


    public void setCommonData(CommonData value) {
        this.commonData = value;
    }


	public TMarkaAutomobila getMarkaAutomobila() {
		return markaAutomobila;
	}


	public void setMarkaAutomobila(TMarkaAutomobila markaAutomobila) {
		this.markaAutomobila = markaAutomobila;
	}


	public List<Automobil> getAutomobil() {
		return automobil;
	}


	public void setAutomobil(List<Automobil> automobil) {
		this.automobil = automobil;
	}
    
    

}
