//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 07:25:52 PM CEST 
//

package com.example.Messages.SchemaToJava2.model.tentitet;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for TModel_automobila complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TModel_automobila">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="naziv_modela" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Common_data" type="{http://www.ftn.uns.ac.rs/AdminKlijent}common_data"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TModel_automobila", propOrder = {
    "id",
    "nazivModela",
    "commonData"
})
@Entity
public class TModelAutomobila {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    protected Long id;
	
	@Column(name = "naziv_modela", nullable = false)
    @XmlElement(name = "naziv_modela", required = true)
    protected String nazivModela;
	
    @XmlElement(name = "Common_data", required = true)
    @Column(name = "common_data_id", nullable = false)
    protected Long commonDataId;
    
	//Jedan TModelAutomobilaa se odnosi na samo jednu TMarkaAutomobila(druga strana bidirekcije)
    @Column(name = "marka_automobila_id", nullable = false)
    private Long markaAutomobilaId;

  	
    public TModelAutomobila(Long id, String nazivModela, Long commonDataId, Long markaAutomobilaId) {
		super();
		this.id = id;
		this.nazivModela = nazivModela;
		this.commonDataId = commonDataId;
		this.markaAutomobilaId = markaAutomobilaId;
	}

	public TModelAutomobila() {
		super();
	}

	public Long getId() {
        return id;
    }


    public void setId(Long value) {
        this.id = value;
    }


    public String getNazivModela() {
        return nazivModela;
    }


    public void setNazivModela(String value) {
        this.nazivModela = value;
    }

	public Long getCommonDataId() {
		return commonDataId;
	}

	public void setCommonDataId(Long commonDataId) {
		this.commonDataId = commonDataId;
	}

	public Long getMarkaAutomobilaId() {
		return markaAutomobilaId;
	}

	public void setMarkaAutomobilaId(Long markaAutomobilaId) {
		this.markaAutomobilaId = markaAutomobilaId;
	}

}
