//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 07:25:52 PM CEST 
//


package com.example.Messages.SchemaToJava2.model.entitet;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import com.example.Messages.SchemaToJava2.model.tentitet.TAdresa;
import com.example.Messages.SchemaToJava2.model.tentitet.TKlasaAutomobila;
import com.example.Messages.SchemaToJava2.model.tentitet.TMarkaAutomobila;
import com.example.Messages.SchemaToJava2.model.tentitet.TModelAutomobila;
//import com.example.Messages.SchemaToJava2.model.tentitet.TSlikaVozila;
//import com.example.Messages.SchemaToJava2.model.tentitet.TTipGoriva;
//import com.example.Messages.SchemaToJava2.model.tentitet.TTipMenjaca;
//import com.example.Messages.SchemaToJava2.model.user.Administrator;
//import com.example.Messages.SchemaToJava2.model.user.Agent;
//import com.example.Messages.SchemaToJava2.model.user.Firma;
//import com.example.Messages.SchemaToJava2.model.user.RegistrovaniKorisnik;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Status_QNAME = new QName("http://www.ftn.uns.ac.rs/korisnici", "Status");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model
     * 
     */
    public ObjectFactory() {
    }

//    /**
//     * Create an instance of {@link Poruka }
//     * 
//     */
//    public Poruka createPoruka() {
//        return new Poruka();
//    }

    /**
     * Create an instance of {@link TModelAutomobila }
     * 
     */
    public TModelAutomobila createTModelAutomobila() {
        return new TModelAutomobila();
    }

    /**
     * Create an instance of {@link TKlasaAutomobila }
     * 
     */
    public TKlasaAutomobila createTKlasaAutomobila() {
        return new TKlasaAutomobila();
    }

//    /**
//     * Create an instance of {@link Pretrazivanje }
//     * 
//     */
//    public Pretrazivanje createPretrazivanje() {
//        return new Pretrazivanje();
//    }

    /**
     * Create an instance of {@link TSlikaVozila }
     * 
     */
//    public TSlikaVozila createTSlikaVozila() {
//        return new TSlikaVozila();
//    }

    /**
     * Create an instance of {@link TTipGoriva }
     * 
     */
//    public TTipGoriva createTTipGoriva() {
//        return new TTipGoriva();
//    }

//    /**
//     * Create an instance of {@link RegistrovaniKorisnik }
//     * 
//     */
//    public RegistrovaniKorisnik createRegistrovaniKorisnik() {
//        return new RegistrovaniKorisnik();
//    }
//
//    /**
//     * Create an instance of {@link Agent }
//     * 
//     */
//    public Agent createAgent() {
//        return new Agent();
//    }

    /**
     * Create an instance of {@link TMarkaAutomobila }
     * 
     */
    public TMarkaAutomobila createTMarkaAutomobila() {
        return new TMarkaAutomobila();
    }

//    /**
//     * Create an instance of {@link Cenovnik }
//     * 
//     */
//    public Cenovnik createCenovnik() {
//        return new Cenovnik();
//    }

    /**
     * Create an instance of {@link Automobil }
     * 
     */
    public Automobil createAutomobil() {
        return new Automobil();
    }

//    /**
//     * Create an instance of {@link Ocena }
//     * 
//     */
//    public Ocena createOcena() {
//        return new Ocena();
//    }
//
//    /**
//     * Create an instance of {@link Rezervacija }
//     * 
//     */
//    public Rezervacija createRezervacija() {
//        return new Rezervacija();
//    }
//
//    /**
//     * Create an instance of {@link Firma }
//     * 
//     */
//    public Firma createFirma() {
//        return new Firma();
//    }
//
//    /**
//     * Create an instance of {@link Administrator }
//     * 
//     */
//    public Administrator createAdministrator() {
//        return new Administrator();
//    }

//    /**
//     * Create an instance of {@link TAdresa.Kordinate }
//     * 
//     */
//    public TAdresa.Kordinate createTAdresaKordinate() {
//        return new TAdresa.Kordinate();
//    }

    /**
     * Create an instance of {@link Oglas }
     * 
     */
//    public Oglas createOglas() {
//        return new Oglas();
//    }
//
//    /**
//     * Create an instance of {@link Komentar }
//     * 
//     */
//    public Komentar createKomentar() {
//        return new Komentar();
//    }

    /**
     * Create an instance of {@link TTipMenjaca }
     * 
     */
//    public TTipMenjaca createTTipMenjaca() {
//        return new TTipMenjaca();
//    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/korisnici", name = "Status", defaultValue = "aktivan")
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

}
