//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 07:25:52 PM CEST 
//


package com.example.Messages.SchemaToJava2.model.entitet;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Korisnik" type="{http://www.ftn.uns.ac.rs/AdminKlijent}common_data"/>
 *         &lt;element name="Vrednost_ocene">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "korisnik",
    "vrednostOcene"
})
@XmlRootElement(name = "Ocena")
@Entity 
public class Ocena {
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    protected Long id;
	
    //Jedna ocena se kreira od strane samo jednog korisnika(druga strana bidirekcije)
    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @XmlElement(name = "Korisnik", required = true)
    protected CommonData korisnik;
    
    @Column(name="vredn_ocene")
    @XmlElement(name = "Vrednost_ocene")
    protected int vrednostOcene;
    
    //Jedna ocena se odnosi na samo jedan automobil(druga strana bidirekcije)
    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private Automobil automobil;

 
    public Long getId() {
        return id;
    }


    public void setId(Long value) {
        this.id = value;
    }


    public CommonData getKorisnik() {
        return korisnik;
    }


    public void setKorisnik(CommonData value) {
        this.korisnik = value;
    }


    public int getVrednostOcene() {
        return vrednostOcene;
    }


    public void setVrednostOcene(int value) {
        this.vrednostOcene = value;
    }


	public Automobil getAutomobil() {
		return automobil;
	}


	public void setAutomobil(Automobil automobil) {
		this.automobil = automobil;
	}

    
}
