//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 07:25:52 PM CEST 
//


package com.example.Messages.SchemaToJava2.model.entitet;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Datum_preuzimanja_vozila" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Datum_povratka_vozila" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Mesto_preuzimanja_vozila" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MinCena" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="MaxCena" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="Dodatni_parametri" type="{http://www.ftn.uns.ac.rs/Automobil}TAutomobila"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datumPreuzimanjaVozila",
    "datumPovratkaVozila",
    "mestoPreuzimanjaVozila",
    "minCena",
    "maxCena",
    "dodatniParametri"
})
@XmlRootElement(name = "Pretrazivanje", namespace = "http://www.ftn.uns.ac.rs/KorisnickiModul")
//@Entity 
public class Pretrazivanje {
	
//	@Id
//	@GeneratedValue(strategy = GenerationType.IDENTITY)
    protected Long id;
	
//	@Column(name="datum_preuz_voz", nullable=false)
    @XmlElement(name = "Datum_preuzimanja_vozila", namespace = "http://www.ftn.uns.ac.rs/KorisnickiModul", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datumPreuzimanjaVozila;
    
//	@Column(name="datum_povr_voz", nullable=false)
    @XmlElement(name = "Datum_povratka_vozila", namespace = "http://www.ftn.uns.ac.rs/KorisnickiModul", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datumPovratkaVozila;
     
//	@Column(name="mesto_preuz_voz", nullable=false)
    @XmlElement(name = "Mesto_preuzimanja_vozila", namespace = "http://www.ftn.uns.ac.rs/KorisnickiModul", required = true)
    protected String mestoPreuzimanjaVozila;
    
//	@Column(name="min_cena", nullable=false)
    @XmlElement(name = "MinCena", namespace = "http://www.ftn.uns.ac.rs/KorisnickiModul", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger minCena;
    
//	@Column(name="max_cena", nullable=false)
    @XmlElement(name = "MaxCena", namespace = "http://www.ftn.uns.ac.rs/KorisnickiModul", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger maxCena;

	public Long getId() {
		return id;
	}


	public void setId(Long id) {
		this.id = id;
	}


    public XMLGregorianCalendar getDatumPreuzimanjaVozila() {
        return datumPreuzimanjaVozila;
    }


    public void setDatumPreuzimanjaVozila(XMLGregorianCalendar value) {
        this.datumPreuzimanjaVozila = value;
    }


    public XMLGregorianCalendar getDatumPovratkaVozila() {
        return datumPovratkaVozila;
    }

    public void setDatumPovratkaVozila(XMLGregorianCalendar value) {
        this.datumPovratkaVozila = value;
    }


    public String getMestoPreuzimanjaVozila() {
        return mestoPreuzimanjaVozila;
    }


    public void setMestoPreuzimanjaVozila(String value) {
        this.mestoPreuzimanjaVozila = value;
    }


    public BigInteger getMinCena() {
        return minCena;
    }


    public void setMinCena(BigInteger value) {
        this.minCena = value;
    }


    public BigInteger getMaxCena() {
        return maxCena;
    }


    public void setMaxCena(BigInteger value) {
        this.maxCena = value;
    }



    
}
