//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 07:25:52 PM CEST 
//


package com.example.Pretraga.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TKlasa_automobila complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TKlasa_automobila">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="naziv_klase" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Common_data" type="{http://www.ftn.uns.ac.rs/AdminKlijent}common_data"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TKlasa_automobila", propOrder = {
    "id",
    "nazivKlase",
    "commonData"
})
@Entity
public class TKlasaAutomobila {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    protected Long id;
	
	@Column(name = "naziv_klase", nullable = false)
    @XmlElement(name = "naziv_klase", required = true)
    protected String nazivKlase;
	
    @XmlElement(name = "Common_data", required = true)
    @Column(name = "commonDataId", nullable = false)
    protected Long commonDataId;

  	public TKlasaAutomobila() {
  		
  	}
  	
    public TKlasaAutomobila(Long id, String nazivKlase, Long commonDataId) {
		super();
		this.id = id;
		this.nazivKlase = nazivKlase;
		this.commonDataId = commonDataId;
	}


    public Long getId() {
        return id;
    }


    public void setId(Long value) {
        this.id = value;
    }


    public String getNazivKlase() {
        return nazivKlase;
    }


    public void setNazivKlase(String value) {
        this.nazivKlase = value;
    }
    

	public Long getCommonDataId() {
		return commonDataId;
	}
	

	public void setCommonDataId(Long commonDataId) {
		this.commonDataId = commonDataId;
	}
    
}
