//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 07:25:52 PM CEST 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="CenaPoDanu" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Naziv_cenovnika" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PopustZaPreko30Dana" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CenaCollisionDamageWaiver" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="CenaPoKilometru" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "cenaPoDanu",
    "nazivCenovnika",
    "popustZaPreko30Dana",
    "cenaCollisionDamageWaiver",
    "cenaPoKilometru"
})
@XmlRootElement(name = "Cenovnik", namespace = "http://www.ftn.uns.ac.rs/cenovnik")
public class Cenovnik {

    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/cenovnik")
    protected long id;
    @XmlElement(name = "CenaPoDanu", namespace = "http://www.ftn.uns.ac.rs/cenovnik")
    protected int cenaPoDanu;
    @XmlElement(name = "Naziv_cenovnika", namespace = "http://www.ftn.uns.ac.rs/cenovnik", required = true)
    protected String nazivCenovnika;
    @XmlElement(name = "PopustZaPreko30Dana", namespace = "http://www.ftn.uns.ac.rs/cenovnik")
    protected int popustZaPreko30Dana;
    @XmlElement(name = "CenaCollisionDamageWaiver", namespace = "http://www.ftn.uns.ac.rs/cenovnik")
    protected Integer cenaCollisionDamageWaiver;
    @XmlElement(name = "CenaPoKilometru", namespace = "http://www.ftn.uns.ac.rs/cenovnik")
    protected Integer cenaPoKilometru;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the cenaPoDanu property.
     * 
     */
    public int getCenaPoDanu() {
        return cenaPoDanu;
    }

    /**
     * Sets the value of the cenaPoDanu property.
     * 
     */
    public void setCenaPoDanu(int value) {
        this.cenaPoDanu = value;
    }

    /**
     * Gets the value of the nazivCenovnika property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivCenovnika() {
        return nazivCenovnika;
    }

    /**
     * Sets the value of the nazivCenovnika property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivCenovnika(String value) {
        this.nazivCenovnika = value;
    }

    /**
     * Gets the value of the popustZaPreko30Dana property.
     * 
     */
    public int getPopustZaPreko30Dana() {
        return popustZaPreko30Dana;
    }

    /**
     * Sets the value of the popustZaPreko30Dana property.
     * 
     */
    public void setPopustZaPreko30Dana(int value) {
        this.popustZaPreko30Dana = value;
    }

    /**
     * Gets the value of the cenaCollisionDamageWaiver property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCenaCollisionDamageWaiver() {
        return cenaCollisionDamageWaiver;
    }

    /**
     * Sets the value of the cenaCollisionDamageWaiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCenaCollisionDamageWaiver(Integer value) {
        this.cenaCollisionDamageWaiver = value;
    }

    /**
     * Gets the value of the cenaPoKilometru property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCenaPoKilometru() {
        return cenaPoKilometru;
    }

    /**
     * Sets the value of the cenaPoKilometru property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCenaPoKilometru(Integer value) {
        this.cenaPoKilometru = value;
    }

}
