//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 07:25:52 PM CEST 
//


package model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/KreiranjeOglasa}Oglas" maxOccurs="unbounded"/>
 *         &lt;element name="Korisnik" type="{http://www.ftn.uns.ac.rs/korisnici}TUser"/>
 *         &lt;element name="Ukupna_cena" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="Od_datuma" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Do_datuma" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Bundle" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Status_rezervacije">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="PENDING|RESERVED|PAID|CANCELED"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/Automobil}Poruka" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "oglas",
    "korisnik",
    "ukupnaCena",
    "odDatuma",
    "doDatuma",
    "bundle",
    "statusRezervacije",
    "poruka"
})
@XmlRootElement(name = "Rezervacija", namespace = "http://www.ftn.uns.ac.rs/Rezervacija")
public class Rezervacija {

    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/Rezervacija")
    protected long id;
    @XmlElement(name = "Oglas", namespace = "http://www.ftn.uns.ac.rs/KreiranjeOglasa", required = true)
    protected List<Oglas> oglas;
    @XmlElement(name = "Korisnik", namespace = "http://www.ftn.uns.ac.rs/Rezervacija", required = true)
    protected TUser korisnik;
    @XmlElement(name = "Ukupna_cena", namespace = "http://www.ftn.uns.ac.rs/Rezervacija")
    protected double ukupnaCena;
    @XmlElement(name = "Od_datuma", namespace = "http://www.ftn.uns.ac.rs/Rezervacija", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar odDatuma;
    @XmlElement(name = "Do_datuma", namespace = "http://www.ftn.uns.ac.rs/Rezervacija", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar doDatuma;
    @XmlElement(name = "Bundle", namespace = "http://www.ftn.uns.ac.rs/Rezervacija")
    protected Boolean bundle;
    @XmlElement(name = "Status_rezervacije", namespace = "http://www.ftn.uns.ac.rs/Rezervacija", required = true, defaultValue = "PENDING")
    protected String statusRezervacije;
    @XmlElement(name = "Poruka")
    protected List<Poruka> poruka;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the oglas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oglas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOglas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Oglas }
     * 
     * 
     */
    public List<Oglas> getOglas() {
        if (oglas == null) {
            oglas = new ArrayList<Oglas>();
        }
        return this.oglas;
    }

    /**
     * Gets the value of the korisnik property.
     * 
     * @return
     *     possible object is
     *     {@link TUser }
     *     
     */
    public TUser getKorisnik() {
        return korisnik;
    }

    /**
     * Sets the value of the korisnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TUser }
     *     
     */
    public void setKorisnik(TUser value) {
        this.korisnik = value;
    }

    /**
     * Gets the value of the ukupnaCena property.
     * 
     */
    public double getUkupnaCena() {
        return ukupnaCena;
    }

    /**
     * Sets the value of the ukupnaCena property.
     * 
     */
    public void setUkupnaCena(double value) {
        this.ukupnaCena = value;
    }

    /**
     * Gets the value of the odDatuma property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOdDatuma() {
        return odDatuma;
    }

    /**
     * Sets the value of the odDatuma property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOdDatuma(XMLGregorianCalendar value) {
        this.odDatuma = value;
    }

    /**
     * Gets the value of the doDatuma property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDoDatuma() {
        return doDatuma;
    }

    /**
     * Sets the value of the doDatuma property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDoDatuma(XMLGregorianCalendar value) {
        this.doDatuma = value;
    }

    /**
     * Gets the value of the bundle property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBundle() {
        return bundle;
    }

    /**
     * Sets the value of the bundle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBundle(Boolean value) {
        this.bundle = value;
    }

    /**
     * Gets the value of the statusRezervacije property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusRezervacije() {
        return statusRezervacije;
    }

    /**
     * Sets the value of the statusRezervacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusRezervacije(String value) {
        this.statusRezervacije = value;
    }

    /**
     * Gets the value of the poruka property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the poruka property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPoruka().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Poruka }
     * 
     * 
     */
    public List<Poruka> getPoruka() {
        if (poruka == null) {
            poruka = new ArrayList<Poruka>();
        }
        return this.poruka;
    }

}
