//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 07:25:52 PM CEST 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TMarka_automobila complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TMarka_automobila">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="naziv_marke" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Common_data" type="{http://www.ftn.uns.ac.rs/AdminKlijent}common_data"/>
 *         &lt;sequence>
 *           &lt;element name="Model_automobila" type="{http://www.ftn.uns.ac.rs/Automobil}TModel_automobila"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TMarka_automobila", propOrder = {
    "id",
    "nazivMarke",
    "commonData",
    "modelAutomobila"
})
public class TMarkaAutomobila {

    protected long id;
    @XmlElement(name = "naziv_marke", required = true)
    protected String nazivMarke;
    @XmlElement(name = "Common_data", required = true)
    protected CommonData commonData;
    @XmlElement(name = "Model_automobila", required = true)
    protected TModelAutomobila modelAutomobila;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the nazivMarke property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivMarke() {
        return nazivMarke;
    }

    /**
     * Sets the value of the nazivMarke property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivMarke(String value) {
        this.nazivMarke = value;
    }

    /**
     * Gets the value of the commonData property.
     * 
     * @return
     *     possible object is
     *     {@link CommonData }
     *     
     */
    public CommonData getCommonData() {
        return commonData;
    }

    /**
     * Sets the value of the commonData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommonData }
     *     
     */
    public void setCommonData(CommonData value) {
        this.commonData = value;
    }

    /**
     * Gets the value of the modelAutomobila property.
     * 
     * @return
     *     possible object is
     *     {@link TModelAutomobila }
     *     
     */
    public TModelAutomobila getModelAutomobila() {
        return modelAutomobila;
    }

    /**
     * Sets the value of the modelAutomobila property.
     * 
     * @param value
     *     allowed object is
     *     {@link TModelAutomobila }
     *     
     */
    public void setModelAutomobila(TModelAutomobila value) {
        this.modelAutomobila = value;
    }

}
